[build]

[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/x86_64-linux-gnu-gcc"
rustflags = ["-C", "target-cpu=ivybridge"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-cpu=ivybridge"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "target-cpu=skylake"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "target-cpu=native"]

[registries.crates-io]
protocol = "sparse"
